# Generated by Django 3.1.7 on 2021-03-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('company_name', models.CharField(default='-1', max_length=250)),
                ('file_location', models.FileField(upload_to='')),
                ('invoice_info', models.TextField(default='-1')),
            ],
        ),
    ]
